// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-tasks.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's tasks. Filter by status (todo, in_progress, done) and limit result count.",
  inputSchema: {
    status: z.enum(["todo", "in_progress", "done"]).optional().describe("Optional task status to filter by."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("tasks").select("id,title,status,priority,due_date,start_time,end_time,is_priority").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a new task for the signed-in user. Uses the user's first board automatically.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Task title."),
    description: z2.string().optional().describe("Optional longer description."),
    priority: z2.enum(["low", "medium", "high", "urgent"]).optional().describe("Task priority."),
    due_date: z2.string().optional().describe("Optional ISO due date (YYYY-MM-DD or full timestamp)."),
    is_priority: z2.boolean().optional().describe("Mark as top priority for the user.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, priority, due_date, is_priority }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sb2(ctx);
    const userId = ctx.getUserId();
    const { data: board, error: boardErr } = await client.from("boards").select("id").eq("user_id", userId).order("created_at", { ascending: true }).limit(1).maybeSingle();
    if (boardErr) return { content: [{ type: "text", text: boardErr.message }], isError: true };
    if (!board) {
      return {
        content: [{ type: "text", text: "No board found for this user. Create one in the app first." }],
        isError: true
      };
    }
    const payload = {
      user_id: userId,
      board_id: board.id,
      title
    };
    if (description) payload.description = description;
    if (priority) payload.priority = priority;
    if (due_date) payload.due_date = due_date;
    if (typeof is_priority === "boolean") payload.is_priority = is_priority;
    const { data, error } = await client.from("tasks").insert(payload).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created task ${data.id}: ${data.title}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/complete-task.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var complete_task_default = defineTool3({
  name: "complete_task",
  title: "Complete task",
  description: "Mark a task as done by its id.",
  inputSchema: {
    task_id: z3.string().uuid().describe("The task id to mark as complete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb3(ctx).from("tasks").update({ status: "done", completed_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", task_id).eq("user_id", ctx.getUserId()).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Task not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Completed: ${data.title}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/get-today-schedule.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_today_schedule_default = defineTool4({
  name: "get_today_schedule",
  title: "Get today's schedule",
  description: "Return the signed-in user's tasks scheduled for today (in UTC), ordered by start time.",
  inputSchema: {
    date: z4.string().optional().describe("Optional YYYY-MM-DD date to query instead of today (UTC).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const day = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const start = `${day}T00:00:00.000Z`;
    const end = `${day}T23:59:59.999Z`;
    const { data, error } = await sb4(ctx).from("tasks").select("id,title,status,priority,start_time,end_time").eq("user_id", ctx.getUserId()).eq("is_scheduled", true).gte("start_time", start).lte("start_time", end).order("start_time", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { date: day, items: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wwxgajrtmslzklnyplah";
var mcp_default = defineMcp({
  name: "taskos-mcp",
  title: "TaskOS \u2014 Tasks & Schedule",
  version: "0.1.0",
  instructions: "Tools for the signed-in user's tasks and daily schedule. Use `list_tasks` to browse work, `create_task` to add a task, `complete_task` to mark one done, and `get_today_schedule` to see what's on the calendar today.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tasks_default, create_task_default, complete_task_default, get_today_schedule_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
