-- Update demo user's scheduled_calls to include window-transition calls
UPDATE public.user_scheduling_prefs
SET scheduled_calls = '[
  {"id": "morning_standup", "name": "Morning Stand-up", "time": "11:00", "enabled": false, "context": "Daily morning check-in to review tasks and priorities.", "callType": "standup", "commsMode": "phone"},
  {"id": "midday_checkin", "name": "Midday Check-in", "time": "12:30", "enabled": false, "context": "Quick midday sync to track progress.", "callType": "standup", "commsMode": "phone"},
  {"id": "eod_wrapup", "name": "End of Day Wrap-up", "time": "19:00", "enabled": false, "context": "End of day review and next day planning.", "callType": "standup", "commsMode": "phone"},
  {"id": "window_morning", "name": "Morning Kickstart", "time": "06:00", "enabled": true, "callType": "custom", "commsMode": "phone", "context": "[WINDOW:morning]\nMorning kickstart call.\n\nBRANCH 1 (morning tasks exist):\n- Greet: \"Hello Sir.\"\n- List morning tasks for this time window\n- List all remaining tasks for the rest of the day\n- Ask: \"Would you like to confirm these for today, adjust them, or skip?\"\n- If confirm: \"Understood. I will call you back later. Goodbye.\"\n- If adjust: Capture edits, confirm changes.\n\nBRANCH 2 (no morning tasks):\n- Greet: \"Hello Sir.\"\n- Say: \"I am just calling to help you get started with your day. I will call you back in a few hours. Goodbye.\""},
  {"id": "window_business", "name": "Business Hours Start", "time": "09:00", "enabled": true, "callType": "custom", "commsMode": "phone", "context": "[WINDOW:business_hours]\nBusiness hours start call.\n\nBRANCH 1 (tasks in next 3 hours):\n- Greet: \"Hello Sir.\"\n- List tasks for the next few hours\n- Ask: \"Which one do you want to start with?\"\n\nBRANCH 2 (no tasks):\n- Greet: \"Hello Sir.\"\n- Topic jog: Share main business-hour topics being worked on\n- Ask: \"Do you want to work on any of these right now?\"\n- If yes: List tasks under that topic, capture selection, schedule them"},
  {"id": "window_eod", "name": "Daily Wrap-up", "time": "17:00", "enabled": true, "callType": "custom", "commsMode": "phone", "context": "[WINDOW:after_work]\nEnd of day wrap-up call.\n\nWRAP-UP FLOW:\n- Greet: \"Hello Sir.\"\n- Ask: \"Any tasks completed today that I should mark done?\"\n- Ask: \"Any tasks blocked or to move to another day?\"\n- Update statuses accordingly\n\nBRANCH 1 (after-work tasks exist):\n- Remind about after-work tasks\n- Ask: \"Do you want to keep these as-is, adjust them, or skip?\"\n\nBRANCH 2 (no after-work tasks):\n- Topic jog with after-work topics\n- Ask: \"Do you want to work on any of these during this time window?\""},
  {"id": "window_evening", "name": "Evening Start", "time": "19:00", "enabled": true, "callType": "custom", "commsMode": "phone", "context": "[WINDOW:evening]\nEvening start call.\n\nBRANCH 1 (evening tasks exist):\n- Greet: \"Hello Sir, I hope you are enjoying your evening.\"\n- List evening tasks\n- Ask: \"Do you want to confirm, adjust, or skip?\"\n\nBRANCH 2 (no evening tasks):\n- Greet: \"Hello Sir, I hope you are enjoying your evening.\"\n- Topic jog with evening topics\n- Ask: \"Do you want to work on any of these tonight?\""},
  {"id": "window_weekend", "name": "Weekend Morning", "time": "10:00", "enabled": true, "callType": "custom", "commsMode": "phone", "context": "[WINDOW:weekends]\nWeekend morning call (Saturday/Sunday only).\n\nBRANCH 1 (weekend tasks for today):\n- Greet: \"Hello Sir, I hope you get a chance to enjoy your weekend.\"\n- List today''s weekend tasks\n- Ask: \"Do you want to confirm, adjust, or skip?\"\n\nBRANCH 2 (no weekend tasks):\n- Greet: \"Hello Sir, I hope you get a chance to enjoy your weekend.\"\n- Topic jog with life/weekend topics\n- Ask: \"Do you want to work on any of these today?\""}
]'::jsonb,
updated_at = now()
WHERE user_id = '00000000-0000-0000-0000-000000000001';