// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://wwxgajrtmslzklnyplah.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3eGdhanJ0bXNsemtsbnlwbGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDI3MzIsImV4cCI6MjA3Mzk3ODczMn0._M_B3093_wjfFe4vwXmKXVCcw-QG5UhRAT4-H-aGoHE";

// Storage key used by supabase-js for session persistence
// Exported so directAuth.ts can read cached tokens directly
export const STORAGE_KEY = `sb-wwxgajrtmslzklnyplah-auth-token`;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Safe Storage Adapter - Falls back to in-memory if localStorage is blocked
 * This prevents crashes in environments where localStorage is unavailable
 */
const createSafeStorage = (): Storage => {
  // Test if localStorage is available
  try {
    const testKey = '__storage_test__';
    localStorage.setItem(testKey, testKey);
    localStorage.removeItem(testKey);
    console.log('[Supabase] Using localStorage for auth persistence');
    return localStorage;
  } catch (e) {
    console.warn('[Supabase] localStorage unavailable, using in-memory storage');
    // In-memory fallback
    const memoryStorage: Record<string, string> = {};
    return {
      getItem: (key: string) => memoryStorage[key] ?? null,
      setItem: (key: string, value: string) => { memoryStorage[key] = value; },
      removeItem: (key: string) => { delete memoryStorage[key]; },
      clear: () => { Object.keys(memoryStorage).forEach(k => delete memoryStorage[k]); },
      get length() { return Object.keys(memoryStorage).length; },
      key: (index: number) => Object.keys(memoryStorage)[index] ?? null
    };
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});